In [ ]:
import numpy as np
import time
np.set_printoptions(suppress=True, precision=6)


In [ ]:
arr_empty_2x2 = np.empty((2,2))
print("empty 2x2:\n", arr_empty_2x2)

empty 2x2:
 [[0. 0.]
 [0. 0.]]


In [ ]:
arr_ones_4x2 = np.ones((4,2))
print("\nones 4x2:\n", arr_ones_4x2)


ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr_full_3x3_fill7 = np.full((3,3), 7, dtype=int)
print("\nfull 3x3 filled with 7:\n", arr_full_3x3_fill7)


full 3x3 filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
sample = np.array([[1,2,3],[4,5,6]])
arr_zeros_like_sample = np.zeros_like(sample)
print("\nzeros_like sample:\n", arr_zeros_like_sample)


zeros_like sample:
 [[0 0 0]
 [0 0 0]]


In [ ]:
arr_ones_like_sample = np.ones_like(sample)
print("\nones_like sample:\n", arr_ones_like_sample)


ones_like sample:
 [[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1,2,3,4]
arr_from_list = np.array(new_list)
print("\narray from list:", arr_from_list)


array from list: [1 2 3 4]


In [ ]:
arr_10_to_49 = np.arange(10,50)
print("10..49:", arr_10_to_49)

10..49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
mat_3x3_0_8 = np.arange(9).reshape((3,3))
print("\n3x3 matrix 0..8:\n", mat_3x3_0_8)


3x3 matrix 0..8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
id_3x3 = np.eye(3, dtype=int)
print("\n3x3 identity:\n", id_3x3)


3x3 identity:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
rand30 = np.random.random(30)
mean_rand30 = rand30.mean()
print("\nrandom(30) mean:", mean_rand30)


random(30) mean: 0.49523814678666006


In [ ]:
rand10x10 = np.random.random((10,10))
min_10x10 = rand10x10.min()
max_10x10 = rand10x10.max()
print("\n10x10 min:", min_10x10, "max:", max_10x10)


10x10 min: 0.003724436820827015 max: 0.9991674810211209


In [ ]:
zero10 = np.zeros(10, dtype=int)
zero10[4] = 1  # 5th element is index 4
print("\nzero10 with 5th element 1:", zero10)


zero10 with 5th element 1: [0 0 0 0 1 0 0 0 0 0]


In [ ]:
arr = np.array([1,2,0,0,4,0])
arr_reversed = arr[::-1]
print("\noriginal:", arr, "reversed:", arr_reversed)


original: [1 2 0 0 4 0] reversed: [0 4 0 0 2 1]


In [ ]:
def border_matrix(n):
    m = np.zeros((n,n), dtype=int)
    m[0,:] = 1
    m[-1,:] = 1
    m[:,0] = 1
    m[:,-1] = 1
    return m

border_5 = border_matrix(5)
print("\n5x5 border matrix:\n", border_5)


5x5 border matrix:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
checker = np.indices((8,8)).sum(axis=0) % 2
print("\n8x8 checkerboard:\n", checker)


8x8 checkerboard:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
add_xy = x + y
print("x + y:\n", add_xy)

x + y:
 [[ 6  8]
 [10 13]]


In [ ]:
sub_xy = x - y
print("\nx - y:\n", sub_xy)



x - y:
 [[-4 -4]
 [-4 -3]]


In [ ]:
mul_x3 = x * 3
print("\nx * 3:\n", mul_x3)


x * 3:
 [[ 3  6]
 [ 9 15]]


In [ ]:
square_x = x**2
print("\nx squared:\n", square_x)


x squared:
 [[ 1  4]
 [ 9 25]]


In [ ]:
dot_v_w = np.dot(v, w)
dot_x_v = x.dot(v)
dot_x_y = x.dot(y)
print("\nDot v.w:", dot_v_w)
print("Dot x.v:", dot_x_v)
print("Dot x.y:\n", dot_x_y)


Dot v.w: 219
Dot x.v: [29 77]
Dot x.y:
 [[19 22]
 [50 58]]


In [ ]:
concat_xy_axis0 = np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))
print("\nconcat x,y along rows:\n", concat_xy_axis0)
print("\nconcat v,w as columns:\n", concat_vw_col)


concat x,y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

concat v,w as columns:
 [[ 9 11]
 [10 12]]


In [ ]:
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\nconcat x and v result:\n", concat_x_v)
except Exception as e:
    print("\nConcatenating x and v raised an error as expected:")
    print("Error:", e)
    print("Explanation: x has shape", x.shape, "but v has shape", v.shape,
          "— cannot concatenate along axis 0 because dimensions don't match.")


Concatenating x and v raised an error as expected:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x has shape (2, 2) but v has shape (2,) — cannot concatenate along axis 0 because dimensions don't match.


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
I = np.eye(2, dtype=float)

A_inv = np.linalg.inv(A)
prod_A_Ainv = A.dot(A_inv)
print("A * A_inv:\n", prod_A_Ainv)


A * A_inv:
 [[1. 0.]
 [0. 1.]]


In [ ]:
AB = A.dot(B)
BA = B.dot(A)
print("\nA*B:\n", AB)
print("\nB*A:\n", BA)
print("\nAre AB and BA equal?", np.allclose(AB, BA))


A*B:
 [[23 13]
 [51 29]]

B*A:
 [[36 44]
 [13 16]]

Are AB and BA equal? False


In [ ]:
lhs = (A.dot(B)).T
rhs = B.T.dot(A.T)
print("\n(AB)^T:\n", lhs)
print("\nB^T A^T:\n", rhs)
print("\n(AB)^T == B^T A^T ?", np.allclose(lhs, rhs))
coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]], dtype=float)
rhs_vec = np.array([-1, -3, 9], dtype=float)

solution = np.linalg.solve(coeff, rhs_vec)
print("\nSolution (using np.linalg.solve):", solution)

coeff_inv = np.linalg.inv(coeff)
solution_via_inv = coeff_inv.dot(rhs_vec)
print("Solution (via inverse):", solution_via_inv)

print("Solutions equal?", np.allclose(solution, solution_via_inv))


(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]

(AB)^T == B^T A^T ? True

Solution (using np.linalg.solve): [ 2.  1. -2.]
Solution (via inverse): [ 2.  1. -2.]
Solutions equal? True


In [ ]:
import random
import time

N = 1_000_000
M = 1000
list1 = [random.random() for _ in range(N)]
list2 = [random.random() for _ in range(N)]

# Python lists addition (element-wise)
t0 = time.time()
list_add = [list1[i] + list2[i] for i in range(N)]
t1 = time.time()
print("Python lists element-wise addition time:", t1 - t0, "seconds")

# NumPy arrays addition
a1 = np.array(list1)
a2 = np.array(list2)
t0 = time.time()
np_add = a1 + a2
t1 = time.time()
print("NumPy arrays addition time:", t1 - t0, "seconds")

Python lists element-wise addition time: 0.10189461708068848 seconds
NumPy arrays addition time: 0.004497051239013672 seconds


In [ ]:
# 2. Element-wise multiplication
t0 = time.time()
list_mul = [list1[i] * list2[i] for i in range(N)]
t1 = time.time()
print("Python lists element-wise multiplication time:", t1 - t0, "seconds")

t0 = time.time()
np_mul = a1 * a2
t1 = time.time()
print("NumPy arrays multiplication time:", t1 - t0, "seconds")


Python lists element-wise multiplication time: 0.11006045341491699 seconds
NumPy arrays multiplication time: 0.004372358322143555 seconds


In [ ]:
# 3. Dot product
t0 = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(N))
t1 = time.time()
print("Python lists dot product time:", t1 - t0, "seconds")

t0 = time.time()
dot_np = a1.dot(a2)
t1 = time.time()
print("NumPy dot product time:", t1 - t0, "seconds")

Python lists dot product time: 0.09739375114440918 seconds
NumPy dot product time: 0.0018663406372070312 seconds


In [ ]:
# 4. Matrix multiplication 1000x1000
A_np = np.random.random((M,M))
B_np = np.random.random((M,M))

t0 = time.time()
C_np = A_np.dot(B_np)
t1 = time.time()
print(f"NumPy matrix multiplication {M}x{M} time:", t1 - t0, "seconds")

M_small = 200
A_list = [[random.random() for _ in range(M_small)] for _ in range(M_small)]
B_list = [[random.random() for _ in range(M_small)] for _ in range(M_small)]

t0 = time.time()
C_list = [[0.0]*M_small for _ in range(M_small)]
for i in range(M_small):
    for k in range(M_small):
        aik = A_list[i][k]
        rowC = C_list[i]
        rowB = B_list[k]
        for j in range(M_small):
            rowC[j] += aik * rowB[j]
t1 = time.time()
print(f"Pure-Python list matrix multiplication {M_small}x{M_small} time:", t1 - t0, "seconds")
print("Note: pure-Python 1000x1000 would take a very long time; NumPy is the practical approach.")

NumPy matrix multiplication 1000x1000 time: 0.14939022064208984 seconds
Pure-Python list matrix multiplication 200x200 time: 2.521402359008789 seconds
Note: pure-Python 1000x1000 would take a very long time; NumPy is the practical approach.


In [ ]:
coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]], dtype=float)
rhs_vec = np.array([-1, -3, 9], dtype=float)

solution = np.linalg.solve(coeff, rhs_vec)
print("\nSolution (using np.linalg.solve):", solution)

coeff_inv = np.linalg.inv(coeff)
solution_via_inv = coeff_inv.dot(rhs_vec)
print("Solution (via inverse):", solution_via_inv)

print("Solutions equal?", np.allclose(solution, solution_via_inv))


Solution (using np.linalg.solve): [ 2.  1. -2.]
Solution (via inverse): [ 2.  1. -2.]
Solutions equal? True
